apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: u-74vf2
    field.cattle.io/ipAddresses: "null"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: rancher-demo
    cattle.io/creator: norman
  name: rancher-demo
  namespace: rancher-demo
  selfLink: /api/v1/namespaces/rancher-demo/services/rancher-demo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: rancher-demo
  sessionAffinity: None
  type: LoadBalancer
status:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
  labels:
    app: rancher-demo
  namespace: rancher-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-demo
  template:
    metadata:
      labels:
        app: rancher-demo
        commit: ${CICD_GIT_COMMIT}
    spec:
      imagePullSecrets:
        - name: gcr
      containers:
        - name: rancher-demo
          image: monachus/rancher-demo
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: rancher-demo
  annotations:
    field.cattle.io/projectId: c-fq8xv:p-rpvpt