stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:lastest
      pushRemote: true
      registry: 127.0.0.1:34573
branch:
  include:
  - master
notification: {}
