stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancher-demo:latest
      pushRemote: true
      registry: 127.0.0.1:34573
notification: {}
