stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:lastest
      pushRemote: true
      registry: gcr.io/imed-cl
  when:
    branch:
      include:
      - master
    event:
      include:
      - push
      - pull_request
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/PROD-G/deployment.yaml
  when:
    branch:
      include:
      - master
    event:
      include:
      - push
      - pull_request
branch:
  include:
  - master
notification: {}
