stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:lastest
      pushRemote: true
      registry: https://hub.docker.com/u/infoubicatecl/
# - name: Deploy
#   when:
#     branch: master
#     event: [ push, pull_request ]
#   steps:
#   - applyYamlConfig:
#       path: ./deploy/PROD-G/deployment.yaml
# branch:
#   include: [ master ]
notification: {}
