apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
spec:
  selector:
    matchLabels:
      app: rancher-demo
  replicas: 1 
  template: 
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
      - name: rancher-demo
        image: infoubicatecl/rancher-demo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: rancher-demo
spec:
 type: NodePort
 selector:
   app: rancher-demo
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: rancher-demo



