apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobBaseName
  labels:
    app: jobBaseName
    version: "version"
    build: "numberBuildJob"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobBaseName
  template:
    metadata:
      labels:
        app: jobBaseName
    spec:
      containers:
        - name: jobBaseName
          image: imageRegistry/appVersion
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources: {}
      restartPolicy: Always
status: {}
