apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobBaseName
  labels:
    app: jobBaseName
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobBaseName
  template:
    metadata:
      labels:
        app: jobBaseName
        version: "{{Version}}"
        build: "numberBuildJob"
    spec:
      containers:
        - name: jobBaseName
          image: imageRegistry/appVersion
          env:
            - name: TZ
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/ash", "-c", "apk add tzdata && cp /usr/share/zoneinfo/$TZ /etc/localtime && apk del tzdata && date"]
          resources: {}
      restartPolicy: Always
status: {}
